# Generated by Django 4.2.13 on 2024-05-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baocaodoanhthu',
            fields=[
                ('mabaocao', models.CharField(db_column='maBaoCao', max_length=6, primary_key=True, serialize=False)),
                ('thang', models.IntegerField(blank=True, null=True)),
                ('nam', models.IntegerField(blank=True, null=True)),
                ('tongdoanhthu', models.DecimalField(blank=True, db_column='tongDoanhThu', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'BaoCaoDoanhThu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('maca', models.CharField(db_column='maCa', max_length=6, primary_key=True, serialize=False)),
                ('tenca', models.CharField(blank=True, db_column='tenCa', max_length=20, null=True)),
                ('giobatdau', models.TimeField(blank=True, db_column='gioBatDau', null=True)),
                ('gioketthuc', models.TimeField(blank=True, db_column='gioKetThuc', null=True)),
            ],
            options={
                'db_table': 'Ca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietdichvu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matieccuoi', models.CharField(db_column='maTiecCuoi', max_length=6)),
                ('madichvu', models.CharField(db_column='maDichVu', max_length=6)),
                ('soluong', models.IntegerField(blank=True, db_column='soLuong', null=True)),
                ('dongiadichvu', models.DecimalField(blank=True, db_column='donGiaDichVu', decimal_places=2, max_digits=15, null=True)),
                ('thanhtien', models.DecimalField(blank=True, db_column='thanhTien', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'ChiTietDichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChitietDvThanhtoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadon', models.CharField(db_column='maHoaDon', max_length=6)),
                ('madichvu', models.CharField(db_column='maDichVu', max_length=6)),
                ('soluong', models.IntegerField(blank=True, db_column='soLuong', null=True)),
                ('dongiadichvu', models.DecimalField(blank=True, db_column='donGiaDichVu', decimal_places=2, max_digits=15, null=True)),
                ('thanhtien', models.DecimalField(blank=True, db_column='thanhTien', decimal_places=2, max_digits=15, null=True)),
                ('ghichu', models.TextField(blank=True, db_column='ghiChu', null=True)),
            ],
            options={
                'db_table': 'ChiTiet_DV_ThanhToan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietmonan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamonan', models.CharField(db_column='maMonAn', max_length=6)),
                ('dongiamonan', models.DecimalField(blank=True, db_column='donGiaMonAn', decimal_places=2, max_digits=15, null=True)),
                ('soluong', models.IntegerField(blank=True, db_column='soLuong', null=True)),
                ('ghichu', models.TextField(blank=True, db_column='ghiChu', null=True)),
            ],
            options={
                'db_table': 'ChiTietMonAn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chucvu',
            fields=[
                ('machucvu', models.CharField(db_column='maChucVu', max_length=6, primary_key=True, serialize=False)),
                ('tenchucvu', models.CharField(blank=True, db_column='tenChucVu', max_length=30, null=True)),
            ],
            options={
                'db_table': 'ChucVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Congviec',
            fields=[
                ('macongviec', models.CharField(db_column='maCongViec', max_length=6, primary_key=True, serialize=False)),
                ('tencongviec', models.CharField(blank=True, db_column='tenCongViec', max_length=40, null=True)),
            ],
            options={
                'db_table': 'CongViec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dichvu',
            fields=[
                ('madichvu', models.CharField(db_column='maDichVu', max_length=6, primary_key=True, serialize=False)),
                ('tendichvu', models.CharField(blank=True, db_column='tenDichVu', max_length=30, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('dongia', models.DecimalField(blank=True, db_column='donGia', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('mahoadon', models.CharField(db_column='maHoaDon', max_length=6, primary_key=True, serialize=False)),
                ('ngaythanhtoan', models.DateField(db_column='ngayThanhToan')),
                ('tongtiendichvu', models.DecimalField(blank=True, db_column='tongTienDichVu', decimal_places=2, max_digits=15, null=True)),
                ('tienphat', models.DecimalField(blank=True, db_column='tienPhat', decimal_places=2, max_digits=15, null=True)),
                ('tongtienhoadon', models.DecimalField(blank=True, db_column='tongTienHoaDon', decimal_places=2, max_digits=15, null=True)),
                ('conlai', models.DecimalField(blank=True, db_column='conLai', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'HoaDon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaimonan',
            fields=[
                ('maloaimonan', models.CharField(db_column='maLoaiMonAn', max_length=6, primary_key=True, serialize=False)),
                ('tenloaimonan', models.CharField(blank=True, db_column='tenLoaiMonAn', max_length=30, null=True)),
            ],
            options={
                'db_table': 'LoaiMonAn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaisanh',
            fields=[
                ('maloaisanh', models.CharField(db_column='maLoaiSanh', max_length=6, primary_key=True, serialize=False)),
                ('tenloaisanh', models.CharField(blank=True, db_column='tenLoaiSanh', max_length=50, null=True)),
                ('dongiabantoithieu', models.DecimalField(blank=True, db_column='donGiaBanToiThieu', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'LoaiSanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monan',
            fields=[
                ('mamonan', models.CharField(db_column='maMonAn', max_length=6, primary_key=True, serialize=False)),
                ('tenmonan', models.CharField(blank=True, db_column='tenMonAn', max_length=30, null=True)),
                ('dongia', models.DecimalField(blank=True, db_column='donGia', decimal_places=2, max_digits=15, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'MonAn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manhanvien', models.CharField(db_column='maNhanVien', max_length=6, primary_key=True, serialize=False)),
                ('tennhanvien', models.CharField(blank=True, db_column='tenNhanVien', max_length=40, null=True)),
                ('gioitinh', models.CharField(blank=True, db_column='gioiTinh', max_length=15, null=True)),
                ('sdt', models.CharField(blank=True, max_length=11, null=True)),
                ('loainhanvien', models.CharField(blank=True, db_column='loaiNhanVien', max_length=20, null=True)),
            ],
            options={
                'db_table': 'NhanVien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phancong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manhanvien', models.CharField(db_column='maNhanVien', max_length=6)),
                ('matieccuoi', models.CharField(db_column='maTiecCuoi', max_length=6)),
            ],
            options={
                'db_table': 'PhanCong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieudattieccuoi',
            fields=[
                ('matieccuoi', models.CharField(db_column='maTiecCuoi', max_length=6, primary_key=True, serialize=False)),
                ('ngaydat', models.DateField(blank=True, db_column='ngayDat', null=True)),
                ('ngaydaitiec', models.DateField(blank=True, db_column='ngayDaiTiec', null=True)),
                ('soluongban', models.IntegerField(blank=True, db_column='soLuongBan', null=True)),
                ('soluongbandutru', models.IntegerField(blank=True, db_column='soLuongBanDuTru', null=True)),
                ('dongiaban', models.DecimalField(blank=True, db_column='donGiaBan', decimal_places=2, max_digits=15, null=True)),
                ('tongtienban', models.DecimalField(blank=True, db_column='tongTienBan', decimal_places=2, max_digits=15, null=True)),
                ('tongtiendichvu', models.DecimalField(blank=True, db_column='tongTienDichVu', decimal_places=2, max_digits=15, null=True)),
                ('tongtiendattiec', models.DecimalField(blank=True, db_column='tongTienDatTiec', decimal_places=2, max_digits=15, null=True)),
                ('tiendatcoc', models.DecimalField(blank=True, db_column='tienDatCoc', decimal_places=2, max_digits=15, null=True)),
                ('conlai', models.DecimalField(blank=True, db_column='conLai', decimal_places=2, max_digits=15, null=True)),
                ('tencodau', models.CharField(blank=True, db_column='tenCoDau', max_length=30, null=True)),
                ('tenchure', models.CharField(blank=True, db_column='tenChuRe', max_length=30, null=True)),
                ('sdt', models.CharField(blank=True, max_length=10, null=True)),
                ('tinhtrangphancong', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PhieuDatTiecCuoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanh',
            fields=[
                ('masanh', models.CharField(db_column='maSanh', max_length=6, primary_key=True, serialize=False)),
                ('tensanh', models.CharField(blank=True, db_column='tenSanh', max_length=50, null=True)),
                ('soluongbantoida', models.IntegerField(blank=True, db_column='soLuongBanToiDa', null=True)),
                ('img', models.ImageField(upload_to='images')),
                ('ghichu', models.TextField(blank=True, db_column='ghiChu', null=True)),
            ],
            options={
                'db_table': 'Sanh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('username', models.CharField(db_column='userName', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='passWord', max_length=100, null=True)),
                ('img', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'TaiKhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thamso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiemtraphat', models.IntegerField(blank=True, db_column='KiemTraPhat', null=True)),
                ('tilephat', models.DecimalField(blank=True, db_column='TiLePhat', decimal_places=2, max_digits=15, null=True)),
                ('tiledatcoc', models.DecimalField(blank=True, db_column='TiLeDatCoc', decimal_places=2, max_digits=15, null=True)),
                ('tgphathuytiec', models.IntegerField(blank=True, db_column='TGPhatHuyTiec', null=True)),
                ('thoigiandattiec', models.IntegerField(blank=True, db_column='thoiGianDatTiec', null=True)),
            ],
            options={
                'db_table': 'ThamSo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietbaocao',
            fields=[
                ('mabaocao', models.OneToOneField(db_column='maBaoCao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.baocaodoanhthu')),
                ('ngay', models.DateField()),
                ('soluongtiec', models.IntegerField(blank=True, db_column='soLuongTiec', null=True)),
                ('doanhthu', models.DecimalField(blank=True, db_column='doanhThu', decimal_places=2, max_digits=15, null=True)),
                ('tile', models.FloatField(blank=True, db_column='tiLe', null=True)),
            ],
            options={
                'db_table': 'ChiTietBaoCao',
                'managed': False,
            },
        ),
    ]
