# Generated by Django 5.0.4 on 2024-05-17 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baocaodoanhthu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ca",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chitietbaocao",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chitietdichvu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chitietdvthanhtoan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chitietmonan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chucvu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="congviec",
            options={},
        ),
        migrations.AlterModelOptions(
            name="dichvu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hoadon",
            options={},
        ),
        migrations.AlterModelOptions(
            name="loaimonan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="loaisanh",
            options={},
        ),
        migrations.AlterModelOptions(
            name="monan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nhanvien",
            options={},
        ),
        migrations.AlterModelOptions(
            name="phancong",
            options={},
        ),
        migrations.AlterModelOptions(
            name="phieudattieccuoi",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sanh",
            options={},
        ),
        migrations.AlterModelOptions(
            name="taikhoan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="thamso",
            options={},
        ),
    ]
