# Generated by Django 4.2.13 on 2024-05-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_baocaodoanhthu_options_alter_ca_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baocaodoanhthu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ca',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chitietbaocao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chitietdichvu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chitietdvthanhtoan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chitietmonan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chucvu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='congviec',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dichvu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loaimonan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loaisanh',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='monan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='phancong',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='phieudattieccuoi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sanh',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='taikhoan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='thamso',
            options={'managed': False},
        ),
    ]
